INSERT INTO currency values
(0,'Afghanistan','AFN')
,(1,'Albania','ALL')
,(2,'Algeria','DZD')
,(3,'American Samoa','USD')
,(4,'Andorra','EUR')
,(5,'Angola','AOA')
,(6,'Anguilla','XCD')
,(7,'Antarctica','XCD')
,(8,'Antigua and Barbuda','XCD')
,(9,'Argentina','ARS')
,(10,'Armenia','AMD')
,(11,'Aruba','AWG')
,(12,'Australia','AUD')
,(13,'Austria','EUR')
,(14,'Azerbaijan','AZN')
,(15,'Bahamas','BSD')
,(16,'Bahrain','BHD')
,(17,'Bangladesh','BDT')
,(18,'Barbados','BBD')
,(19,'Belarus','BYR')
,(20,'Belgium','EUR')
,(21,'Belize','BZD')
,(22,'Benin','XOF')
,(23,'Bermuda','BMD')
,(24,'Bhutan','BTN')
,(25,'Bolivia','BOB')
,(26,'Bosnia-Herzegovina','BAM')
,(27,'Botswana','BWP')
,(28,'Bouvet Island','NOK')
,(29,'Brazil','BRL')
,(30,'British Indian Ocean Territory','USD')
,(31,'Brunei Darussalam','BND')
,(32,'Bulgaria','BGN')
,(33,'Burkina Faso','XOF')
,(34,'Burundi','BIF')
,(35,'Cambodia','KHR')
,(36,'Cameroon','XAF')
,(37,'Canada','CAD')
,(38,'Cape Verde','CVE')
,(39,'Cayman Islands','KYD')
,(40,'Central African Republic','XAF')
,(41,'Chad','XAF')
,(42,'Chile','CLP')
,(43,'China','CNY')
,(44,'Christmas Island','AUD')
,(45,'Cocos (Keeling) Islands','AUD')
,(46,'Colombia','COP')
,(47,'Comoros','KMF')
,(48,'Congo','XAF')
,(49,'Congo, Dem. Republic','CDF')
,(50,'Cook Islands','NZD')
,(51,'Costa Rica','CRC')
,(52,'Croatia','HRK')
,(53,'Cuba','CUP')
,(54,'Cyprus','EUR')
,(55,'Czech Rep.','CZK')
,(56,'Denmark','DKK')
,(57,'Djibouti','DJF')
,(58,'Dominica','XCD')
,(59,'Dominican Republic','DOP')
,(60,'Ecuador','ECS')
,(61,'Egypt','EGP')
,(62,'El Salvador','SVC')
,(63,'Equatorial Guinea','XAF')
,(64,'Eritrea','ERN')
,(65,'Estonia','EUR')
,(66,'Ethiopia','ETB')
,(67,'European Union','EUR')
,(68,'Falkland Islands (Malvinas)','FKP')
,(69,'Faroe Islands','DKK')
,(70,'Fiji','FJD')
,(71,'Finland','EUR')
,(72,'France','EUR')
,(73,'French Guiana','EUR')
,(74,'French Southern Territories','EUR')
,(75,'Gabon','XAF')
,(76,'Gambia','GMD')
,(77,'Georgia','GEL')
,(78,'Germany','EUR')
,(79,'Ghana','GHS')
,(80,'Gibraltar','GIP')
,(81,'Great Britain','GBP')
,(82,'Greece','EUR')
,(83,'Greenland','DKK')
,(84,'Grenada','XCD')
,(85,'Guadeloupe (French)','EUR')
,(86,'Guam (USA)','USD')
,(87,'Guatemala','QTQ')
,(88,'Guernsey','GGP')
,(89,'Guinea','GNF')
,(90,'Guinea Bissau','GWP')
,(91,'Guyana','GYD')
,(92,'Haiti','HTG')
,(93,'Heard Island and McDonald Islands','AUD')
,(94,'Honduras','HNL')
,(95,'Hong Kong','HKD')
,(96,'Hungary','HUF')
,(97,'Iceland','ISK')
,(98,'India','INR')
,(99,'Indonesia','IDR')
,(100,'Iran','IRR')
,(101,'Iraq','IQD')
,(102,'Ireland','EUR')
,(103,'Isle of Man','GBP')
,(104,'Israel','ILS')
,(105,'Italy','EUR')
,(106,'Ivory Coast','XOF')
,(107,'Jamaica','JMD')
,(108,'Japan','JPY')
,(109,'Jersey','GBP')
,(110,'Jordan','JOD')
,(111,'Kazakhstan','KZT')
,(112,'Kenya','KES')
,(113,'Kiribati','AUD')
,(114,'Korea-North','KPW')
,(115,'Korea-South','KRW')
,(116,'Kuwait','KWD')
,(117,'Kyrgyzstan','KGS')
,(118,'Laos','LAK')
,(119,'Latvia','LVL')
,(120,'Lebanon','LBP')
,(121,'Lesotho','LSL')
,(122,'Liberia','LRD')
,(123,'Libya','LYD')
,(124,'Liechtenstein','CHF')
,(125,'Lithuania','LTL')
,(126,'Luxembourg','EUR')
,(127,'Macau','MOP')
,(128,'Macedonia','MKD')
,(129,'Madagascar','MGF')
,(130,'Malawi','MWK')
,(131,'Malaysia','MYR')
,(132,'Maldives','MVR')
,(133,'Mali','XOF')
,(134,'Malta','EUR')
,(135,'Marshall Islands','USD')
,(136,'Martinique (French)','EUR')
,(137,'Mauritania','MRO')
,(138,'Mauritius','MUR')
,(139,'Mayotte','EUR')
,(140,'Mexico','MXN')
,(141,'Micronesia','USD')
,(142,'Moldova','MDL')
,(143,'Monaco','EUR')
,(144,'Mongolia','MNT')
,(145,'Montenegro','EUR')
,(146,'Montserrat','XCD')
,(147,'Morocco','MAD')
,(148,'Mozambique','MZN')
,(149,'Myanmar','MMK')
,(150,'Namibia','NAD')
,(151,'Nauru','AUD')
,(152,'Nepal','NPR')
,(153,'Netherlands','EUR')
,(154,'Netherlands Antilles','ANG')
,(155,'New Caledonia (French)','XPF')
,(156,'New Zealand','NZD')
,(157,'Nicaragua','NIO')
,(158,'Niger','XOF')
,(159,'Nigeria','NGN')
,(160,'Niue','NZD')
,(161,'Norfolk Island','AUD')
,(162,'Northern Mariana Islands','USD')
,(163,'Norway','NOK')
,(164,'Oman','OMR')
,(165,'Pakistan','PKR')
,(166,'Palau','USD')
,(167,'Panama','PAB')
,(168,'Papua New Guinea','PGK')
,(169,'Paraguay','PYG')
,(170,'Peru','PEN')
,(171,'Philippines','PHP')
,(172,'Pitcairn Island','NZD')
,(173,'Poland','PLN')
,(174,'Polynesia (French)','XPF')
,(175,'Portugal','EUR')
,(176,'Puerto Rico','USD')
,(177,'Qatar','QAR')
,(178,'Reunion (French)','EUR')
,(179,'Romania','RON')
,(180,'Russia','RUB')
,(181,'Rwanda','RWF')
,(182,'Saint Helena','SHP')
,(183,'Saint Kitts &amp; Nevis Anguilla','XCD')
,(184,'Saint Lucia','XCD')
,(185,'Saint Pierre and Miquelon','EUR')
,(186,'Saint Vincent &amp; Grenadines','XCD')
,(187,'Samoa','WST')
,(188,'San Marino','EUR')
,(189,'Sao Tome and Principe','STD')
,(190,'Saudi Arabia','SAR')
,(191,'Senegal','XOF')
,(192,'Serbia','RSD')
,(193,'Seychelles','SCR')
,(194,'Sierra Leone','SLL')
,(195,'Singapore','SGD')
,(196,'Slovakia','EUR')
,(197,'Slovenia','EUR')
,(198,'Solomon Islands','SBD')
,(199,'Somalia','SOS')
,(200,'South Africa','ZAR')
,(201,'South Georgia &amp; South Sandwich Islands','GBP')
,(202,'South Sudan','SSP')
,(203,'Spain','EUR')
,(204,'Sri Lanka','LKR')
,(205,'Sudan','SDG')
,(206,'Suriname','SRD')
,(207,'Svalbard and Jan Mayen Islands','NOK')
,(208,'Swaziland','SZL')
,(209,'Sweden','SEK')
,(210,'Switzerland','CHF')
,(211,'Syria','SYP')
,(212,'Taiwan','TWD')
,(213,'Tajikistan','TJS')
,(214,'Tanzania','TZS')
,(215,'Thailand','THB')
,(216,'Togo','XOF')
,(217,'Tokelau','NZD')
,(218,'Tonga','TOP')
,(219,'Trinidad and Tobago','TTD')
,(220,'Tunisia','TND')
,(221,'Turkey','TRY')
,(222,'Turkmenistan','TMT')
,(223,'Turks and Caicos Islands','USD')
,(224,'Tuvalu','AUD')
,(225,'U.K.','GBP')
,(226,'Uganda','UGX')
,(227,'Ukraine','UAH')
,(228,'United Arab Emirates','AED')
,(229,'Uruguay','UYU')
,(230,'USA','USD')
,(231,'USA Minor Outlying Islands','USD')
,(232,'Uzbekistan','UZS')
,(233,'Vanuatu','VUV')
,(234,'Vatican','EUR')
,(235,'Venezuela','VEF')
,(236,'Vietnam','VND')
,(237,'Virgin Islands (British)','USD')
,(238,'Virgin Islands (USA)','USD')
,(239,'Wallis and Futuna Islands','XPF')
,(240,'Western Sahara','MAD')
,(241,'Yemen','YER')
,(242,'Zambia','ZMW')
,(243,'Zimbabwe','ZWD')
,(1,'Afghanistan','AFN')
,(2,'Albania','ALL')
,(3,'Algeria','DZD')
,(4,'American Samoa','USD')
,(5,'Andorra','EUR')
,(6,'Angola','AOA')
,(7,'Anguilla','XCD')
,(8,'Antarctica','XCD')
,(9,'Antigua and Barbuda','XCD')
,(10,'Argentina','ARS')
,(11,'Armenia','AMD')
,(12,'Aruba','AWG')
,(13,'Australia','AUD')
,(14,'Austria','EUR')
,(15,'Azerbaijan','AZN')
,(16,'Bahamas','BSD')
,(17,'Bahrain','BHD')
,(18,'Bangladesh','BDT')
,(19,'Barbados','BBD')
,(20,'Belarus','BYR')
,(21,'Belgium','EUR')
,(22,'Belize','BZD')
,(23,'Benin','XOF')
,(24,'Bermuda','BMD')
,(25,'Bhutan','BTN')
,(26,'Bolivia','BOB')
,(27,'Bosnia-Herzegovina','BAM')
,(28,'Botswana','BWP')
,(29,'Bouvet Island','NOK')
,(30,'Brazil','BRL')
,(31,'British Indian Ocean Territory','USD')
,(32,'Brunei Darussalam','BND')
,(33,'Bulgaria','BGN')
,(34,'Burkina Faso','XOF')
,(35,'Burundi','BIF')
,(36,'Cambodia','KHR')
,(37,'Cameroon','XAF')
,(38,'Canada','CAD')
,(39,'Cape Verde','CVE')
,(40,'Cayman Islands','KYD')
,(41,'Central African Republic','XAF')
,(42,'Chad','XAF')
,(43,'Chile','CLP')
,(44,'China','CNY')
,(45,'Christmas Island','AUD')
,(46,'Cocos (Keeling) Islands','AUD')
,(47,'Colombia','COP')
,(48,'Comoros','KMF')
,(49,'Congo','XAF')
,(50,'Congo, Dem. Republic','CDF')
,(51,'Cook Islands','NZD')
,(52,'Costa Rica','CRC')
,(53,'Croatia','HRK')
,(54,'Cuba','CUP')
,(55,'Cyprus','EUR')
,(56,'Czech Rep.','CZK')
,(57,'Denmark','DKK')
,(58,'Djibouti','DJF')
,(59,'Dominica','XCD')
,(60,'Dominican Republic','DOP')
,(61,'Ecuador','ECS')
,(62,'Egypt','EGP')
,(63,'El Salvador','SVC')
,(64,'Equatorial Guinea','XAF')
,(65,'Eritrea','ERN')
,(66,'Estonia','EUR')
,(67,'Ethiopia','ETB')
,(68,'European Union','EUR')
,(69,'Falkland Islands (Malvinas)','FKP')
,(70,'Faroe Islands','DKK')
,(71,'Fiji','FJD')
,(72,'Finland','EUR')
,(73,'France','EUR')
,(74,'French Guiana','EUR')
,(75,'French Southern Territories','EUR')
,(76,'Gabon','XAF')
,(77,'Gambia','GMD')
,(78,'Georgia','GEL')
,(79,'Germany','EUR')
,(80,'Ghana','GHS')
,(81,'Gibraltar','GIP')
,(82,'Great Britain','GBP')
,(83,'Greece','EUR')
,(84,'Greenland','DKK')
,(85,'Grenada','XCD')
,(86,'Guadeloupe (French)','EUR')
,(87,'Guam (USA)','USD')
,(88,'Guatemala','QTQ')
,(89,'Guernsey','GGP')
,(90,'Guinea','GNF')
,(91,'Guinea Bissau','GWP')
,(92,'Guyana','GYD')
,(93,'Haiti','HTG')
,(94,'Heard Island and McDonald Islands','AUD')
,(95,'Honduras','HNL')
,(96,'Hong Kong','HKD')
,(97,'Hungary','HUF')
,(98,'Iceland','ISK')
,(99,'India','INR')
,(100,'Indonesia','IDR')
,(101,'Iran','IRR')
,(102,'Iraq','IQD')
,(103,'Ireland','EUR')
,(104,'Isle of Man','GBP')
,(105,'Israel','ILS')
,(106,'Italy','EUR')
,(107,'Ivory Coast','XOF')
,(108,'Jamaica','JMD')
,(109,'Japan','JPY')
,(110,'Jersey','GBP')
,(111,'Jordan','JOD')
,(112,'Kazakhstan','KZT')
,(113,'Kenya','KES')
,(114,'Kiribati','AUD')
,(115,'Korea-North','KPW')
,(116,'Korea-South','KRW')
,(117,'Kuwait','KWD')
,(118,'Kyrgyzstan','KGS')
,(119,'Laos','LAK')
,(120,'Latvia','LVL')
,(121,'Lebanon','LBP')
,(122,'Lesotho','LSL')
,(123,'Liberia','LRD')
,(124,'Libya','LYD')
,(125,'Liechtenstein','CHF')
,(126,'Lithuania','LTL')
,(127,'Luxembourg','EUR')
,(128,'Macau','MOP')
,(129,'Macedonia','MKD')
,(130,'Madagascar','MGF')
,(131,'Malawi','MWK')
,(132,'Malaysia','MYR')
,(133,'Maldives','MVR')
,(134,'Mali','XOF')
,(135,'Malta','EUR')
,(136,'Marshall Islands','USD')
,(137,'Martinique (French)','EUR')
,(138,'Mauritania','MRO')
,(139,'Mauritius','MUR')
,(140,'Mayotte','EUR')
,(141,'Mexico','MXN')
,(142,'Micronesia','USD')
,(143,'Moldova','MDL')
,(144,'Monaco','EUR')
,(145,'Mongolia','MNT')
,(146,'Montenegro','EUR')
,(147,'Montserrat','XCD')
,(148,'Morocco','MAD')
,(149,'Mozambique','MZN')
,(150,'Myanmar','MMK')
,(151,'Namibia','NAD')
,(152,'Nauru','AUD')
,(153,'Nepal','NPR')
,(154,'Netherlands','EUR')
,(155,'Netherlands Antilles','ANG')
,(156,'New Caledonia (French)','XPF')
,(157,'New Zealand','NZD')
,(158,'Nicaragua','NIO')
,(159,'Niger','XOF')
,(160,'Nigeria','NGN')
,(161,'Niue','NZD')
,(162,'Norfolk Island','AUD')
,(163,'Northern Mariana Islands','USD')
,(164,'Norway','NOK')
,(165,'Oman','OMR')
,(166,'Pakistan','PKR')
,(167,'Palau','USD')
,(168,'Panama','PAB')
,(169,'Papua New Guinea','PGK')
,(170,'Paraguay','PYG')
,(171,'Peru','PEN')
,(172,'Philippines','PHP')
,(173,'Pitcairn Island','NZD')
,(174,'Poland','PLN')
,(175,'Polynesia (French)','XPF')
,(176,'Portugal','EUR')
,(177,'Puerto Rico','USD')
,(178,'Qatar','QAR')
,(179,'Reunion (French)','EUR')
,(180,'Romania','RON')
,(181,'Russia','RUB')
,(182,'Rwanda','RWF')
,(183,'Saint Helena','SHP')
,(184,'Saint Kitts &amp; Nevis Anguilla','XCD')
,(185,'Saint Lucia','XCD')
,(186,'Saint Pierre and Miquelon','EUR')
,(187,'Saint Vincent &amp; Grenadines','XCD')
,(188,'Samoa','WST')
,(189,'San Marino','EUR')
,(190,'Sao Tome and Principe','STD')
,(191,'Saudi Arabia','SAR')
,(192,'Senegal','XOF')
,(193,'Serbia','RSD')
,(194,'Seychelles','SCR')
,(195,'Sierra Leone','SLL')
,(196,'Singapore','SGD')
,(197,'Slovakia','EUR')
,(198,'Slovenia','EUR')
,(199,'Solomon Islands','SBD')
,(200,'Somalia','SOS')
,(201,'South Africa','ZAR')
,(202,'South Georgia &amp; South Sandwich Islands','GBP')
,(203,'South Sudan','SSP')
,(204,'Spain','EUR')
,(205,'Sri Lanka','LKR')
,(206,'Sudan','SDG')
,(207,'Suriname','SRD')
,(208,'Svalbard and Jan Mayen Islands','NOK')
,(209,'Swaziland','SZL')
,(210,'Sweden','SEK')
,(211,'Switzerland','CHF')
,(212,'Syria','SYP')
,(213,'Taiwan','TWD')
,(214,'Tajikistan','TJS')
,(215,'Tanzania','TZS')
,(216,'Thailand','THB')
,(217,'Togo','XOF')
,(218,'Tokelau','NZD')
,(219,'Tonga','TOP')
,(220,'Trinidad and Tobago','TTD')
,(221,'Tunisia','TND')
,(222,'Turkey','TRY')
,(223,'Turkmenistan','TMT')
,(224,'Turks and Caicos Islands','USD')
,(225,'Tuvalu','AUD')
,(226,'U.K.','GBP')
,(227,'Uganda','UGX')
,(228,'Ukraine','UAH')
,(229,'United Arab Emirates','AED')
,(230,'Uruguay','UYU')
,(231,'USA','USD')
,(232,'USA Minor Outlying Islands','USD')
,(233,'Uzbekistan','UZS')
,(234,'Vanuatu','VUV')
,(235,'Vatican','EUR')
,(236,'Venezuela','VEF')
,(237,'Vietnam','VND')
,(238,'Virgin Islands (British)','USD')
,(239,'Virgin Islands (USA)','USD')
,(240,'Wallis and Futuna Islands','XPF')
,(241,'Western Sahara','MAD')
,(242,'Yemen','YER')
,(243,'Zambia','ZMW')
,(244,'Zimbabwe','ZWD')
